### ISSUE TITLE
[Feature] Compile future builds for arm 32-bit and x86_64

### ISSUE THREAD

**Issue by PalmDevs** [pastthepixels/FreePaint#23] opened 2024-05-11 22:41 UTC
**Describe the bug**
Latest release (`v1.2.0`) build does not contain the necessary libraries for other architectures.

**To Reproduce**
1. Download latest release
2. Install it on a device not running on ARMv8
3. Observe failure

**Expected behavior**
Installation not failing. Necessary libraries are included for other architectures in the build.

**Device (please complete the following information):**
 - OS/version: One UI 6.0
 - Device: Samsung Galaxy A13
 - Version: Android 14

**Comment by pastthepixels** [comment] 2024-05-26 20:14
Changing the title as this is not a bug -- this is expected behavior from the compiled APK -- but rather a feature request to compile to other architectures. FreePaint is actually compiled for arm64-v8a (64-bit ARM processors), not armeabi-v7a as you mentioned. However, your phone either has an ARM Cortex-A55 or A76 processor which are both 64 bit and can run FreePaint. I'll try and compile the next version for other architectures, but in the meantime I would suggest looking at your software setup or even contacting Samsung as you might have a 32-bit OS installed.

**Comment by PalmDevs** [comment] 2024-05-26 20:17
> but in the meantime I would suggest looking at your software setup or even contacting Samsung as you might have a 32-bit OS installed.

Unfortunately this is intentionally done by Samsung to some older lower-end devices to reduce resource usage. I can't do anything much about it. 🫠

Although previous builds do work with ARMv7 devices, did anything change?

**Comment by pastthepixels** [comment] 2024-05-26 20:49
> Although previous builds do work with ARMv7 devices, did anything change?

I had a look and it seems like [pathway](https://github.com/romainguy/pathway) may have dropped support for anything except arm64-v8a. I can compile the application itself for other architectures, but if Pathway doesn't support those architectures that'll be a little difficult

**Comment by pastthepixels** [comment] 2024-08-20 19:39
I just made a change to compile to armeabi (32-bit) and x86_64 architectures - and it works on an x86_64 virtual machine - but unfortunately I don't have an armeabi machine to test on. Looking at a debug apk I generated though it seems like I can compile universal apks.
If you can compile FreePaint from the 1.3.0 branch I would recommend testing it out but right now I am like 90% sure it compiles universal apks again.

**Comment by pastthepixels** [comment] 2024-11-10 08:07
Update: Turns out this actually introduced some bugs. On the plus side, I rewrote all the code that used Pathway while working on rewriting the eraser tool so FreePaint doesn't use it anymore (!)
I'll be closing this issue since this kinda fixed the root of the problem but please feel free to re-open it if that code won't work for other architectures.

**Closed by pastthepixels** 2024-11-10 08:07 UTC
