### ISSUE TITLE
[Bug] FreePaint Bug Report (v1.0.2)

### ISSUE THREAD

**Issue by TechMorgan** [pastthepixels/FreePaint#26] opened 2024-05-24 07:09 UTC
1. App crashes when double tapping while using paint brush and eraser.

2.  When using the eraser, instead of creating a closed path to erase the entire segment, I want an option to use a normal eraser to erase specified amount of the line based on where I slide on it.

**Device**
 - OS/version: Oxygen OS (Android 13)
 - Device: OnePlus Nord CE 3

**Comment by pastthepixels** [comment] 2024-05-26 20:21
This may be an issue for 1.0.2, but I can't seem to reproduce it on the latest version of FreePaint, 1.2.0, on stock Android. Could you send a video (or preferably, [logcat](https://developer.android.com/tools/logcat)) of when FreePaint crashes?
Also, you've listed a feature request along with your bug report - since it's unrelated to the bug, please make a separate feature request.
Thanks!

**Comment by TechMorgan** [comment] 2024-06-09 08:57
Now updated it to 1.2.0, bug still exists

https://github.com/pastthepixels/FreePaint/assets/83485038/9bcbd1c9-866a-4537-87cd-2c8708f9110b

**Comment by pastthepixels** [comment] 2024-10-27 22:07
Closing in favour of #30 and #31

**Closed by pastthepixels** 2024-10-27 22:07 UTC
